Day_1: If Else

In [7]:
can = ["Canh", "Tan", "Nham", "Quy", "Giap", "At", "Binh", "Dinh", "Mau", "Ky"]
chi = ["Than", "Dau", "Tuat", "Hoi", "Ty", "Suu", "Dan", "Mao", "Thin", "Ty", "Ngo", "Mui"]

In [8]:
def calculate_can_chi_calendar(year):
  result =''

  can_year = can[year%10]
  chi_year = chi[year%12]
  result = can_year + ' ' + chi_year

  return result

In [9]:
calculate_can_chi_calendar(2024)

'Giap Thin'

In [10]:
calculate_can_chi_calendar(2023)

'Quy Mao'

In [11]:
calculate_can_chi_calendar(1997)

'Dinh Suu'

--------------------------------------------------------------------------------------------

Day_2: For Loop

In [2]:
def compute_interest(money, period):
    result = ''
    
    for iterate in range(period):
        result = (money + (money / period))**period

    return result

In [23]:
compute_interest(1, 12)

2.613035290224676

In [24]:
compute_interest(1, 365)

2.7145674820219727

In [25]:
compute_interest(1, 730)

2.7164223264603464

In [3]:
compute_interest(1, 1730)

2.7174966139216066

--------------------------------------------------------------------------------------------

Day_3: While-Loop

In [4]:
def find_squared_root (a):
    epsilon = 0.001
    result = ''
    x_n = a
    
    while True:
        # tinh xn+1
        x_n1 = 0.5 * (x_n + a / x_n)

        # dieu kien dung
        if abs(x_n1 - x_n) < epsilon:
            return x_n1
        
        # cap nhat x_n
        x_n = x_n1

In [5]:
find_squared_root(2)

1.4142135623746899

In [6]:
find_squared_root(3)

1.7320508100147274

--------------------------------------------------------------------------------------------

Day_4: 2D List - Convolutional calculation

In [5]:
# Hàm tính tích chập (convolution) cho ma trận
def convolution_2d(matrix, kernel):
    m, n = len(matrix), len(matrix[0])
    km, kn = len(kernel), len(kernel[0])
    output = []

    for i in range(m - km + 1):
        row = []
        for j in range(n - kn + 1):
            sum = 0
            for ki in range(km):
                for kj in range(kn):
                    sum += matrix[i + ki][j + kj] * kernel[ki][kj]
            row.append(sum)
        output.append(row)
    return output


# Ma trận đầu vào A
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Kernel B
kernel_b = [
    [2, 4],
    [4, 3]
]

# Kernel C
kernel_c = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

# Tính toán Convolutional cho câu A
result_a = convolution_2d(matrix_a, kernel_b)
print("Câu A: Kết quả tích chập của A và Kernel B:")
for row in result_a:
    print(row)

# Tính toán Convolutional cho câu B
result_b = convolution_2d(matrix_a, kernel_c)
print("Câu B: Kết quả tích chập của A và Kernel C:")
for row in result_b:
    print(row)

Câu A: Kết quả tích chập của A và Kernel B:
[41, 54]
[80, 93]
Câu B: Kết quả tích chập của A và Kernel C:
[15]


a_rows = 3
a_cols = 3
b_index = 0
a_metrix = [[0]*a_cols for v in range(a_rows)]
value = 1
ab_metrix = [[0]*(a_cols - 1) for v in range(a_rows - 1)]
ac_metrix = [[0]*a_cols for v in range(a_rows)]
temp_metrix = [[0]*(a_cols - 1) for v in range(a_rows - 1)]
for r in range(a_rows):
    for c in range(a_cols):
        a_metrix[r][c] = value
        value += 1

for v in range(3):
    print(a_metrix[v])
    print()
    
b_metrix = [[2, 4], [1, 3]]
c_metrix = [[1, 1, 1], [0, 0, 0], [1, 1, 1]]

for v in range(2):
    print(b_metrix[v])
    print()

for r in range (a_rows):
    for c in range(a_cols):
        if c > b_index + 1:
            break
        elif r > b_index + 1:
            break
        else:
            ab_metrix[r][c] =  a_metrix[r][c] * b_metrix[b_index][b_index] + \
                                a_metrix[r][c + 1] * b_metrix[b_index][b_index + 1] + \
                                a_metrix[r + 1][c + 1] * b_metrix[b_index + 1][b_index + 1] + \
                                a_metrix[r + 1][c] * b_metrix[b_index + 1][b_index]

print(ab_metrix)

for r in range (a_rows):
    for c in range(a_cols):
        if r == 1 & c == 1:
            ac_metrix[r][c] =  a_metrix[r - 1][c - 1] * c_metrix[r - 1][c - 1] + \
                                a_metrix[r - 1][c] * c_metrix[r - 1][c] + \
                                a_metrix[r - 1][c + 1] * c_metrix[r - 1][c + 1] + \
                                a_metrix[r][c - 1] * c_metrix[r][c - 1] + \
                                a_metrix[r][c + 1] * c_metrix[r][c + 1] + \
                                a_metrix[r + 1][c - 1] * c_metrix[r + 1][c - 1] + \
                                a_metrix[r + 1][c] * c_metrix[r + 1][c] + \
                                a_metrix[r + 1][c + 1] * c_metrix[r + 1][c + 1]
            
for v in range(3):
    print(ac_metrix[v])
    print()


--------------------------------------------------------------------------------------------

Day_5: Bag of Words (NLP)

In [4]:
# Bước 1: Tạo corpus
corpus = [
    "Tôi thích môn Toán",
    "Tôi thích AI",
    "Tôi thích âm nhạc"
]

# Bước 2: Tokenization


def tokenize(sentence):
    return sentence.split()


# Tạo từ vựng (vocabulary) từ corpus
vocabulary = set()
for document in corpus:
    words = tokenize(document)
    vocabulary.update(words)
vocabulary = sorted(vocabulary)

# Tạo dictionary để mapping từ vựng với chỉ số
vocab_dict = {word: idx for idx, word in enumerate(vocabulary)}

# Bước 3: Biểu diễn văn bản dưới dạng BoW


def vectorize(sentence):
    words = tokenize(sentence)
    vector = [0] * len(vocabulary)
    for word in words:
        if word in vocab_dict:
            index = vocab_dict[word]
            vector[index] += 1
    return vector


# Ví dụ sử dụng:
sentence = "Tôi thích AI thích Toán"
bow_vector = vectorize(sentence)

print("Vocabulary:", vocabulary)
print("BoW Vector:", bow_vector)

Vocabulary: ['AI', 'Toán', 'Tôi', 'môn', 'nhạc', 'thích', 'âm']
BoW Vector: [1, 1, 1, 0, 0, 2, 0]


corpus = ["Toi thich mon Toan", "Toi thich AI", "Toi thich am nhac"]
words = "Toi thich AI thich Toan"

bag_of_words = set()
for i in range(len(corpus)):
    temp = set(corpus[i].split())
    bag_of_words.update(temp)

tem = words.split()
cont = [0]*len(bag_of_words)
bag_of_words = list(bag_of_words)
 
for b in range(len(bag_of_words)):
    for i in range(len(tem)):
        if bag_of_words[b] == tem[i]:
            cont[b] += 1


print(bag_of_words)
print(tem)

print(cont)

--------------------------------------------------------------------------------------------

Day_6: 2D List - Convolutional calculation

In [6]:
import numpy as np


def apply_convolution(input_matrix, kernel):
    # Add zero padding around the input matrix
    padded_input = np.pad(input_matrix, ((1, 1), (1, 1)),
                          mode='constant', constant_values=0)

    # Output matrix initialization
    output_matrix = np.zeros(
        (padded_input.shape[0] - kernel.shape[0] + 1, padded_input.shape[1] - kernel.shape[1] + 1))

    # Convolution calculation
    for i in range(output_matrix.shape[0]):
        for j in range(output_matrix.shape[1]):
            output_matrix[i, j] = np.sum(
                padded_input[i:i+kernel.shape[0], j:j+kernel.shape[1]] * kernel)

    return output_matrix


# Input matrix
input_matrix = np.array([
    [0, 0, 0, 0],
    [0, 1, 2, 0],
    [0, 3, 4, 5],
    [6, 7, 8, 0]
])

# Kernel matrix
kernel = np.array([
    [0, 1, 2],
    [1, 2, 3]
])

# Apply convolution
output_matrix = apply_convolution(input_matrix, kernel)

# Print the output matrix
print("Output matrix:")
print(output_matrix)

Output matrix:
[[ 0.  0.  0.  0.]
 [ 3.  8.  5.  2.]
 [11. 23. 28. 14.]
 [39. 55. 37. 13.]
 [20. 23.  8.  0.]]


a_rows = 5
a_cols = 5
b_index = 0
a_metrix = [[0]*a_cols for v in range(a_rows)]
value = 1
ab_metrix = [[0]*(a_cols - 1) for v in range(a_rows - 1)]
ac_metrix = [[0]*a_cols for v in range(a_rows)]
temp_metrix = [[0]*(a_cols - 1) for v in range(a_rows - 1)]


a_metrix[2][2] = 4
a_metrix[3][2] = 1
print("a metrix")
for v in range(a_rows):
    print(a_metrix[v])
    print()

b_metrix = [[1, 1], [1, 1]]
c_metrix = [[0, 1, 0], [0, 1, 0], [0, 1, 0]]
print("b metrix") 
for v in range(len(b_metrix)):
    print(b_metrix[v])
    print()

for r in range (a_rows):
    for c in range(a_cols):
        if c > b_index + 1:
            break
        elif r > b_index + 1:
            break
        else:
            ab_metrix[r][c] =  a_metrix[r][c] * b_metrix[b_index][b_index] + \
                                a_metrix[r][c + 1] * b_metrix[b_index][b_index + 1] + \
                                a_metrix[r + 1][c + 1] * b_metrix[b_index + 1][b_index + 1] + \
                                a_metrix[r + 1][c] * b_metrix[b_index + 1][b_index]

print("ab metrix") 
for v in range(len(ab_metrix)):
    print(ab_metrix[v])
    print()

for r in range (a_rows):
    for c in range(a_cols):
        if c > b_index + 1:
            break
        elif r > b_index + 1:
            break
        if r == 3 & c == 3:
            ac_metrix[r][c] =  a_metrix[r - 1][c - 1] * c_metrix[r - 1][c - 1] + \
                                a_metrix[r - 1][c] * c_metrix[r - 1][c] + \
                                a_metrix[r - 1][c + 1] * c_metrix[r - 1][c + 1] + \
                                a_metrix[r][c - 1] * c_metrix[r][c - 1] + \
                                a_metrix[r][c + 1] * c_metrix[r][c + 1] + \
                                a_metrix[r + 1][c - 1] * c_metrix[r + 1][c - 1] + \
                                a_metrix[r + 1][c] * c_metrix[r + 1][c] + \
                                a_metrix[r + 1][c + 1] * c_metrix[r + 1][c + 1]
print(ac_metrix)

--------------------------------------------------------------------------------------------

Day_7: 2D List - Convolutional calculation

In [8]:

a_metrix = [
    [0, 0, 0, 4],
    [0, 4, 0, 2],
    [0, 1, 0, 2],
    [0, 3, 0, 2]
]

for v in range(len(a_metrix)):
    print(a_metrix[v])
    print()
    

def convolution_2d_max_pooling(matrix):
    m, n = len(matrix), len(matrix[0])
    km, kn = 2, 2
    output = []

    for i in range(0, m - km + 1, 2):
        row = []
        for j in range(0, n - kn + 1, 2):
            max_value = 0
            for ki in range(km):
                for kj in range(kn):
                    temp = matrix[i + ki][j + kj]
                    if temp > max_value:
                        max_value = temp
            row.append(max_value)
        output.append(row)
    return output


print(convolution_2d_max_pooling(a_metrix))


def convolution_2d_ave_pooling(matrix):
    m, n = len(matrix), len(matrix[0])
    km, kn = 2, 2
    output = []

    for i in range(0, m - km + 1, 2):
        row = []
        for j in range(0, n - kn + 1, 2):
            ave = 0
            num_ele = 0
            sum_ele = 0
            for ki in range(km):
                for kj in range(kn):
                    sum_ele += matrix[i + ki][j + kj]
                    num_ele += 1
            ave = sum_ele/num_ele
            row.append(ave)
        output.append(row)
    return output


print(convolution_2d_ave_pooling(a_metrix))




[0, 0, 0, 4]

[0, 4, 0, 2]

[0, 1, 0, 2]

[0, 3, 0, 2]

[[4, 4], [3, 2]]
[[1.0, 1.5], [1.0, 1.0]]


----------------------------------------------------------------------------------------------------

Day_8: Tuple - Cosine Similarity

In [10]:
import math

def dot_product(vec_a, vec_b):
    return sum(a * b for a, b in zip(vec_a, vec_b))

def magnitude(vector):
    return math.sqrt(sum(x**2 for x in vector))

def cosine_similarity(vec_a, vec_b):
    dot_prod = dot_product(vec_a, vec_b)
    mag_a = magnitude(vec_a)
    mag_b = magnitude(vec_b)
    
    if mag_a == 0 or mag_b == 0:
        return 0  # Xử lý trường hợp độ lớn của vector bằng 0 để tránh chia cho 0
    
    return dot_prod / (mag_a * mag_b)

# Vector A và B
vec_a = [1, 2]
vec_b = [4, 5]

# Tính cosine similarity
result = cosine_similarity(vec_a, vec_b)
print(f"Cosine Similarity giữa A và B là: {result}")

Cosine Similarity giữa A và B là: 0.9778024140774094


------------------------------------------------------------------------------


Day_9: OOP

In [11]:
import math

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def distance_to_origin(self):
        return math.sqrt(self.x**2 + self.y**2)

# Tạo đối tượng point_a và point_b
point_a = Point(1, 2)
point_b = Point(4, 5)

# Tính khoảng cách từ point_a và point_b đến gốc tọa độ
distance_a_to_origin = point_a.distance_to_origin()
distance_b_to_origin = point_b.distance_to_origin()

print(f"Khoảng cách từ point_a (1, 2) đến gốc tọa độ là: {distance_a_to_origin}")
print(f"Khoảng cách từ point_b (4, 5) đến gốc tọa độ là: {distance_b_to_origin}")

Khoảng cách từ point_a (1, 2) đến gốc tọa độ là: 2.23606797749979
Khoảng cách từ point_b (4, 5) đến gốc tọa độ là: 6.4031242374328485
